CREATE SCHEMA CRM;
CREATE TABLE CRM.TVRTKA ( 
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
NAZIV VARCHAR(50) NOT NULL, 
OIB VARCHAR(11) NOT NULL, 
PRIMARY KEY (ID) 
); 

INSERT INTO CRM.TVRTKA (NAZIV, OIB) VALUES ('Turbo softver', '61233549876'); 
CREATE TABLE CRM.KLIJENT ( ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
OIB VARCHAR(11) NOT NULL, 
PREZIME VARCHAR(25) NOT NULL, 
IME VARCHAR(25) NOT NULL, 
TELEFON VARCHAR(25) NOT NULL, 
EMAIL VARCHAR(25) NOT NULL, 
DATUM_RODJENJA DATE NOT NULL, 
PRIMARY KEY (ID)
);
INSERT INTO CRM.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('98765432123', 'Periæ', 'Pero', '098777666', 'peric.pero@java.com', '1996-05-01');
INSERT INTO CRM.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('76545678909', 'Iviæ', 'Ivo', '091654321', 'ivic.ivo@eclipse.com', '1998-06-05');
INSERT INTO CRM.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('12345678903', 'Horvat', 'Marko', '098654321', 'marko.horvat@test.hr', '1998-08-13');
CREATE TABLE CRM.TVRTKA_KLIJENT(
TVRTKA_ID INT NOT NULL,
KLIJENT_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, KLIJENT_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES CRM.TVRTKA(ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES CRM.KLIJENT(ID)
);
INSERT INTO CRM.TVRTKA_KLIJENT VALUES (1, 1);
INSERT INTO CRM.TVRTKA_KLIJENT VALUES (1, 2);
INSERT INTO CRM.TVRTKA_KLIJENT VALUES (1, 3);
CREATE TABLE CRM.ZAPOSLENIK(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
KORISNICKO_IME VARCHAR(25) NOT NULL,
PREZIME VARCHAR(25) NOT NULL,
IME VARCHAR(25) NOT NULL,
SIFRA VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO CRM.ZAPOSLENIK(KORISNICKO_IME, PREZIME, IME, SIFRA) VALUES ('ihorvat',
'Ivana', 'Horvat', 'ih543');
INSERT INTO CRM.ZAPOSLENIK(KORISNICKO_IME, PREZIME, IME, SIFRA) VALUES
('mkovacevic', 'Martina', 'Kovaèeviæ', 'mk123');
CREATE TABLE CRM.TVRTKA_ZAPOSLENIK(
TVRTKA_ID INT NOT NULL,
ZAPOSLENIK_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, ZAPOSLENIK_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES CRM.TVRTKA(ID),
FOREIGN KEY(ZAPOSLENIK_ID) REFERENCES CRM.ZAPOSLENIK(ID)
);
INSERT INTO CRM.TVRTKA_ZAPOSLENIK VALUES (1, 1);
INSERT INTO CRM.TVRTKA_ZAPOSLENIK VALUES (1, 2);
CREATE TABLE CRM.KATEGORIJA_ARTIKLA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO CRM.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('SOFTVER');
INSERT INTO CRM.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('ELEKTROTEHNIKA');
INSERT INTO CRM.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('MEHANIKA');
INSERT INTO CRM.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('OSTALO');
CREATE TABLE CRM.ARTIKL(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
KATEGORIJA_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KATEGORIJA_ID ) REFERENCES CRM.KATEGORIJA_ARTIKLA(ID )
);
INSERT INTO CRM.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Mobilna aplikacija', 1);
INSERT INTO CRM.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Web aplikacija', 1);
INSERT INTO CRM.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Edukacija', 4);
CREATE TABLE CRM.TVRTKA_ARTIKL(
TVRTKA_ID INT NOT NULL,
ARTIKL_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, ARTIKL_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES CRM.TVRTKA(ID),
FOREIGN KEY(ARTIKL_ID) REFERENCES CRM.ARTIKL(ID)
);
INSERT INTO CRM.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 1);
INSERT INTO CRM.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 2);
INSERT INTO CRM.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 3);
CREATE TABLE CRM.VRSTA_KOMUNIKACIJE(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO CRM.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('VERBALNA');
INSERT INTO CRM.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('PISMENA');
INSERT INTO CRM.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('ELEKTRONICKA');
INSERT INTO CRM.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('OSTALO');
CREATE TABLE CRM.ALARM(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
OPIS VARCHAR(250) NOT NULL,
KLIJENT_ID INT NOT NULL,
VRIJEME TIMESTAMP NOT NULL,
AKTIVAN BOOLEAN NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES CRM.KLIJENT(ID)
);
CREATE TABLE CRM.KOMUNIKACIJA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
KLIJENT_ID INT NOT NULL,
ZAPOSLENIK_ID INT NOT NULL,
VRSTA_KOMUNIKACIJE_ID INT NOT NULL,
SADRZAJ VARCHAR(500) NOT NULL,
VRIJEME TIMESTAMP NOT NULL,
AKTIVAN BOOLEAN NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES CRM.KLIJENT(ID),
FOREIGN KEY(ZAPOSLENIK_ID) REFERENCES CRM.ZAPOSLENIK(ID),
FOREIGN KEY(VRSTA_KOMUNIKACIJE_ID) REFERENCES CRM.VRSTA_KOMUNIKACIJE(ID)
);
CREATE TABLE CRM.VRSTA_USLUGE(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO CRM.VRSTA_USLUGE (NAZIV) VALUES ('PRODAJNA');
INSERT INTO CRM.VRSTA_USLUGE (NAZIV) VALUES ('PRAVNA');
INSERT INTO CRM.VRSTA_USLUGE (NAZIV) VALUES ('OSTALO');
CREATE TABLE CRM.USLUGA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
OPIS VARCHAR(250) NOT NULL,
KLIJENT_ID INT NOT NULL,
VRSTA_USLUGE_ID INT NOT NULL,
DATUM DATE NOT NULL,
CIJENA DECIMAL(10,2) NOT NULL,
PLACENA BOOLEAN NOT NULL,
OBAVLJENA BOOLEAN NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES CRM.KLIJENT(ID),
FOREIGN KEY(VRSTA_USLUGE_ID ) REFERENCES CRM.VRSTA_USLUGE(ID)
);
